### ISSUE TITLE
BSLODTriShape lacks Spells support

### ISSUE THREAD

**Issue by Ghostwalker71** [niftools/nifskope#1]
A `BSLODTriShape` loses the:

Texture
Mesh
Flags
Transform (sub-options)

...options in the Right-Click context menu.

Most critically (IMO) is the fact that **Update All Tangent Spaces**, et al., do not apply to `BSLODTriShape`. One may think that the tangent spaces get updated on all TriShapes, but they do not.

The only workaround to use UV Edit, Update Tangent Space, etc. is to temporarily rename the block to `NiTriShape`.

**Comment by hexabits** [comment]
After I got NifSkope actually compiling (not this version but nexustheru's, sorry) it was about a 2 minute fix.

**Comment by neomonkeus** [comment]
@jonwd7 
I am not sure what that current condition of this repo as far as getting it to successful compile, i.e if dependancies are outdated, etc. it has only recently (relatively) been moved to github.

If you want to send a patch to this repo, either to get it compiling or the fix you mention that would be great.
- create a branch from develop 
- Name your branch accordingly -> fix/compile, fix/bslodtrishape_handling or super_combined fix :P
- Send a pull request to develop with your fix
- People will review and merge 

@nexustheru's develop branch is not mergeable as a branch should have been created from develop rather than work directly included on it. From looking at the branch we can't really include it anyways as it removes a lot of files as that would need to added back in. Pulling out the fbx importer features into a new branch synch'd against develop would be the better way to go about it.

**Comment by neomonkeus** [comment]
Closed with pull request

Ref : #9
