### ISSUE TITLE
NifSkope_2_0_2016-11-07 won't associate with .nif files

### ISSUE THREAD

**Issue by dwharper34** [niftools/nifskope#103]
I have been using NifSkope on 2 computers. My main computer associates .nif files correctly. It's down right now and my backup computer will not associate ,nif files at all. Both computers are running Windows 7 x64. 

When I try to open a .nif file, I select 'Open with..." and NifSkope is not on the list. I browse to the directory that it resides at and I select NifSkope.exe. Windows does not select it though. I have tried to add it to regedit under HKEY_CLASSES_ROOT .nif. I added 'OpenWithList' and 'NifSkope.exe' below that. It still doesn't work. 

I think my other computer had NifTools installed and that might be why it works. I think a NifSkope installer would allow you to associate ,nif file from the beginning.

I searched for anyone else having this problem and I found many who did, but no one had a solution. I am sure that your team should have the solution though. Any help would be appreciated!

I would like to add that NifSkope is great and has helped me solve many issues. Keep up the good work.

**Comment by Ethreon** [comment]
I would like to also add to this issue. Worked perfectly fine for a long period of time, then, after some windows hiccups and a mistaken association, it refuses to come back to the default state.

**Comment by hexabits** [comment]
This is purely a Windows issue.  You can probably just use the 1.1.3 installer from SourceForge which should fix the association, then delete everything in the install location and extract 2.0 to it.

Anyway there's nothing I can do if you break file associations.  The associations broke because Windows being Windows, not because NifSkope.  I can change my file associations on a whim regardless of build, so I don't believe it's something specific to 2016-11-07 build as the OP would suggest, but a platform issue. 

There are also many third party apps that should be able to fix and manage associations.

**Comment by InsanePlumber** [comment]
[FileTypesMan](http://www.nirsoft.net/utils/file_types_manager.html)  it is a simple and clean application that can help.

**Comment by Ethreon** [comment]
I'm not going to bother with any more applications. The solution I found and solved another program I use is to rename the exe to something else. I was able to redo the association without any issues after.

**Comment by hexabits** [comment]
Going ahead and closing this since it's a Windows issue.  I could try to write a file associations fixer into the application, but there's no guarantee in this case that it would have worked.
