### ISSUE TITLE
Nifskope can't read CK-generated precombined meshes

### ISSUE THREAD

**Issue by VlitS** [niftools/nifskope#106]
Thank you very much for updating nifskope so it can read the Bethesda-made precombined nifs. It's painful figuring out what parts match up to what references, but if I really want to I can edit them.

However, the ones generated by the CK use a completely different format apparently. So they are not only 5-10 times larger than the Bethesda-made ones, but nifskope can't read them. When I open a CK-made precombined, it gives two warnings:

```
File: 
Function: 
Line: 0
Category: nifskope.nif
Message:

"Unknown property: BSShaderTextureSet"
```

and 

```
warning: block 3 (BSPackedCombinedGeomDataExtra) not inserted!
device position incorrect after block number 3 (BSPackedCombinedGeomDataExtra) at 0x228 ended at 0x228 (expected 0x370)
device position incorrect after block number 4 (BSLightingShaderProperty) at 0x370 ended at 0x374 (expected 0x3fc)
device position incorrect after block number 5 (BSShaderTextureSet) at 0x3fc ended at 0x428 (expected 0x445)

```
Any chance of an update to let use clean up the CK-made precombineds for those of use crazy enough to try?

Currently using most up-to-date version I can find: 2.0.dev6 (revision 1d9d0d6)

**Comment by hexabits** [comment]
Strange.  The CK _is_ what Bethesda uses to bake precombined so "Bethesda-made" vs "CK-made" isn't quite how I'd put it.   Though clearly they've somehow changed the process at some point.   I will have to check the vanilla precombined for the DLC, especially Nuka World, as maybe they migrated to the new format.

You are right that it's a completely different format.  I almost missed it but your error message says `BSPackedCombinedGeomDataExtra` which isn't even the same block as vanilla precomb.   The vanilla precomb uses `BSPackedCombinedSharedGeomDataExtra`. 

I didn't even know the former existed as it wasn't in anything vanilla.  I will need example files to decode it, barring their presence in the DLC.  Could you please share the files you've made with the CK @VlitS ?  It would probably take a lot longer (or indefinitely) if I were to need to generate my own precombined to decode it.

**Comment by VlitS** [comment]
I've long had doubts about that claim. Maybe it started as the tool they used, but if so they've taken a hacksaw to it before giving it to us.

Checking both Nukaworld and Automatron, the precombined meshes are completely readable, so it's not a change they made for their use. These meshes were made in the CK around the same time as Nukaworld was released: [https://drive.google.com/open?id=0Bygv1CyEB6z1R2JTRmFvRm9zUkE](https://drive.google.com/open?id=0Bygv1CyEB6z1R2JTRmFvRm9zUkE)

**Comment by Iloei** [comment]
Given some of the release-time flaws of the games, I suspect the reverse - that they polished it before releasing it to the public.

**Comment by hexabits** [comment]
>Maybe it started as the tool they used, but if so they've taken a hacksaw to it before giving it to us.

Well that's never been a debate.  They have always crippled the public version of the CK.  It is still based on what they used though, so having a completely different format for precombined means either 

1. It's a format they moved to.
2. It's a format they moved away from.

And since it's not present in any of the DLC I think we can rule out 1.  

There is also the possibility that it has something to do with the state of your cell or the items in the cell and this format is chosen for a reason.   Is it a vanilla cell in a vanilla worldspace?  Is it a completely new cell?  And so on.   I guess sometime I will try regenerating the precombined for an entirely vanilla cell and see what it does. 

It's "funny" that you said that they're 5x larger... I've massively criticized the entire system for how it completely crippled half of all mesh modding (statics) and have said that if you were to try to do something like SMIM it's basically impossible without disabling the system or regenerating the precombined for every cell... which amounts to 2GB+ of extra data.  But if the CK we have access to makes 5x larger files then we're looking at 10GB+ of precombined data...  In which case there is zero hope of having a mod like SMIM while still using the precomb/vis system.

>Given some of the release-time flaws of the games, I suspect the reverse - that they polished it before releasing it to the public.

This is without doubt not the case.  Entire sections of the CK often do not work or crash and this has been that way since Oldrim.  They strip out a lot of things that they don't have the license to redistribute as well. 

----

Anyway, @VlitS, it'll probably take me a while to decode this new block.  I first need to migrate `BSPackedCombinedSharedGeomDataExtra` to my [010 template](https://github.com/jonwd7/0x6e6966746f6f6c73/tree/master/nif) which I use for decoding.  I can tell you already though that `BSPackedCombinedSharedGeomDataExtra` and `BSPackedCombinedGeomDataExtra` are definitely not aliases.  Sometimes "new" blocks in Bethesda NIFs are just another block with a different name.  That is not the case here.
