### ISSUE TITLE
Unable to add resource folder

### ISSUE THREAD

**Issue by pakanek** [niftools/nifskope#114]
Open file window in `Options->Settings->Resources->Add Folder` does not accept directories (only files).

My version is 2.0.0 Pre-Alpha 6.

**Comment by hexabits** [comment]
![unknown](https://user-images.githubusercontent.com/170077/28232135-1df2d65a-68bd-11e7-94da-b2007f0a93ed.png)

The Add Folder window is a standard Windows file dialog and it is set specifically to allow folders.   There is nothing for me to fix because at that point it is up to Windows to show the correct dialog. 

Maybe you are in the Archives tab and don't realize it, since you said `Resources->Add Folder` when actually it's either  `Resources->Paths->Add Folder` or `Resources->Archives->Add Folder`. 

Anyway, you double click on a folder to navigate to it and then press "Select Folder" like any other file dialog where you can choose folders.

**Comment by pakanek** [comment]
I am running it in Wine. I fixed it by switching from Win XP to Win 7 emulation mode in winecfg.
