### ISSUE TITLE
Application not opening

### ISSUE THREAD

**Issue by Satvik662** [niftools/nifskope#121]
Whenever I double click nifscope.exe, it doesn't open. Please help!

**Comment by mindflvx** [comment]
I remember having the same problem at some point on Windows 10.

Go to the installation folder and rename the executable to "Nifskope2.exe" or something like that, then try running it (obviously the executable, not the shortcut).

**Comment by Satvik662** [comment]
Still don't work.

**Comment by josephcrowell** [comment]
Please come to the Discord chat for general help. The issue tracker is for actual bugs.
https://discord.gg/dbvQzJ

**Comment by hexabits** [comment]
There was zero information provided but I am assuming it's likely due to faulty/over-zealous AV heuristics or firewalls.  This can't be fixed on NifSkope's end.  The program opens on a normal computer.  The only time I've been unable to open NifSkope was on a VM without OpenGL drivers, but they haven't even said if they are on a laptop or a normal desktop and if they have a dedicated GPU or not, so we can't do anything with this ticket.
