### ISSUE TITLE
Crashing without warning on startup

### ISSUE THREAD

**Issue by Bomo99** [niftools/nifskope#138]
My old pc that had Nifskope installed stopped working 6 months ago i decided to finally install to a laptop that i had(not the greatest but gets the job done except this)and i downloaded this version NifSkope 2.0 Dev 7, 2-3 weeks ago and i have tried to get it to work with no avail i found an old version NifSkope 2.0 Pre-Alpha 6, to see if it was that my laptop cant load the newest version and that didnt work. Could it be my hardware that my laptop has?
Operating System: Windows 7 Professional
Processor: Intel Core I3-2330M Cpu @ 2.20GHz
Ram: 4 Gb
System Type 64-Bit Operating System
For my old pc i can only remember this
Operating System: Windows 7 Professional
Processor: 
Ram: 4 Gb
System Type 64-Bit Operating System
any help would be appreciated even if it is that my laptop cant run this program

**Comment by RichardIsADeadMan** [comment]
Hey Bomo, sounds like you were having the same problem that I was with version 2.0, my Lenovo laptop's specs are about the same as yours and it would refuse to run Nifskope 2.0. I searched the web for weeks to find a solution to no avail. I ended up deleting it and reverting back to the stable 1.2 Alpha version which open and works like a charm, Most of the additions to 2.0 aren't necessary for most work that we would do with nif meshes so you might want to roll back to the 1.2 version until the new bugs get worked out. Cheers!

**Comment by hexabits** [comment]
There are no new bugs @RichardIsADeadMan ... Intel HD Graphics drivers are particularly awful with OpenGL support.  This is not my opinion, it is widely known and Intel doesn't care.  2.0 "does more" with OpenGL and Intel drivers apparently don't support it.  The only thing I could possibly do is fix the OpenGL initialization to fail slightly better so that you can at least open NIFs, but not render them, since I don't know what new features your OpenGL drivers aren't supporting. 

Also I don't know where you are getting "stable" from.  1.2 was not a stable release, it was an alpha release.  2.0 is just as "stable" as 1.2. 

The only way I could really figure out what exactly Intel is breaking on is if I got a laptop with integrated graphics.  So this is not very likely to be fixed unless someone with a laptop will work closely with me, which everyone who has reported issues vanishes and doesn't seem to care after the initial report so it's not like I even have that option.

**Comment by hexabits** [comment]
>it was never my intention

![untitled-1](https://user-images.githubusercontent.com/170077/39607880-afbad21a-4f0b-11e8-9ed2-7d9d8a5698eb.png)

If this was already filtered to come off more nicely, then your thoughts are really:

- 2.0 is unstable and unnecessary.
- Instead of posting in the Discord or the forums or on GitHub I would rather roam the internet aimlessly for "weeks" trying to fix it myself.
- Don't bother with helping the developer find the actual issue, just downgrade to 1.2.
- Make sure he knows I downgraded to 1.2, and try to get others to downgrade to 1.2.
- Bugs that are a result of my integrated graphics will eventually work themselves out.
- That I have a specific hardware combination that doesn't work with the program (that I allegedly was interested in solving) in no way obligates me to help the developer. 

Having these thoughts is fine, but posting them on an issue in the project's repo is overtly malicious.  That you made an account just to do it only adds to it.  Basically, you made an account to tell people to not use 2.0, but you couldn't make an account at any point during the weeks you were searching for answers.

>touched on a sore nerve

Subtle but still implying that, to you, everything you said was perfectly fine and it's me who has the problem, i.e. I'm too sensitive. 

>offer some help

Coming in here and telling anyone reading to not help me, and instead just downgrade is help?  Am I really being sensitive if someone is trying to actively hinder progress on the issue?

>sorry dude, but I am quite happy with what I can do with 1.2

Then you are posting here why?  Why does a happy person create an account just for these posts?  Where is the person who searched for **weeks** to find a solution?  Why didn't that person create an account?  Are they too busy still looking to double click on a debug build that I send them and send me back logs?

**Comment by neomonkeus** [comment]
Adding deleted comments (what I could find) that @jonwd7 was responding to

> Hey Bomo, sounds like you were having the same problem that I was with version 2.0, my Lenovo laptop's specs are about the same as yours and it would refuse to run Nifskope 2.0. I searched the web for weeks to find a solution to no avail. I ended up deleting it and reverting back to the stable 1.2 Alpha version which open and works like a charm, Most of the additions to 2.0 aren't necessary for most work that we would do with nif meshes so you might want to roll back to the 1.2 version until...

> Jon, sorry if I touched on a sore nerve there, it was never my intention. I really appreciate all the work you've done with your releases and was simply using layman's terms with Bomo to offer some help since I've had similar issues with my craptop pc (Intel HD is indeed terrible). I'm not nearly knowledgeable enough to help you with the OpenGL on Intel drivers, sorry dude, but I am quite happy with what I can do with 1.2.

Closing as no response from original poster about the actual issue that was reported.
