### ISSUE TITLE
NifSkope consistently corrupts unedited vanilla file when saving it

### ISSUE THREAD

**Issue by opusGlass** [niftools/nifskope#144]
NifSkope consistently corrupts the Skyrim Legendary Edition file \Data\meshes\actors\horse\character assets\harness.nif when saving. If you open the unedited vanilla file then click Save without altering anything, the file looks fine, but causes instant CTD in-game (I'm loading near Whiterun stables). The only difference I see after saving is that the NiTriShape at node 12 is moved to the top of the file instead of its original location at the bottom.

This is tested with 2.0 dev 7 as well as an earlier version (number uknown -- the first thing I tried when I encountered the issue was upgrading nifskope).

Vanilla, uncorrupted version of the file attached.
[harness.zip](https://github.com/niftools/nifskope/files/2195109/harness.zip)

**Comment by hexabits** [comment]
That is not the definition of "corruption".  The file remains valid.  

It cannot be helped that a certain block order is required for this NIF by an ESM/ESP.  There are several systems that require the block order to be unchanged.  You could also attempt to replace the NIF entirely with another completely valid NIF and have the same effect. 

The reason it's crashing is because you're not modifying the records that reference this NIF to use the new block order, and this has nothing to do with NifSkope and everything to do with the Creation Kit. 

Edit: 
Which, without auto-sanitize on, it would produce a binary identical file.  If you need a certain block order for a NIF in game,  you need to turn auto-sanitize off.

**Comment by opusGlass** [comment]
> turn auto-sanitize off

Okay, that's the answer I was looking for, thanks.

**Comment by hexabits** [comment]
@opusGlass  That's not the "answer" though.  There are more NIFs that *will* crash the game with **auto-sanitize off** than will crash the game with auto-sanitize on and for different reasons.  You will end up not sanitizing block names or clearing None Refs and those are far more dangerous than block order issues, which are relatively few and far between.

**Comment by opusGlass** [comment]
I'm not sure why you're being combative, I never claimed that auto-sanitize should be turned off for every nif. It was the answer I was looking for because it's the information I needed in order to work with the nif in question.

**Comment by hexabits** [comment]
I'm not being "combative"...  Maybe you're projecting?

I was emphasizing that you'll break more NIFs with it off, which is exactly what I said and nothing more..

**Comment by jonwd7** [comment]
Also, if I was being combative or not, I'm not sure what exactly you think accusing me of it on a public GitHub issue was going to do, other than further provocation.  So I must conclude that provocation was your intent and you are the one being combative.  For future reference, personal attacks on a GitHub issue are not a good way to get future help.

Furthermore

>I never claimed that auto-sanitize should be turned off for every nif. It was the answer I was looking for because it's the information I needed in order to work with the nif in question.

Even though I never said you claimed this, you're stating this as if it were obvious, or somehow wrapped up in your previous comment:

![asgdadgsgsdgs](https://user-images.githubusercontent.com/170077/42729232-b18f7eee-879e-11e8-974b-6d8c2adfaf5a.png)

Where it actually seems quite probable you were never going to use auto-sanitize again, due to the complete removal of context from my sentence.  You managed to reduce what I said to "Turn auto-sanitize off", which is not what I said, hence my need to elaborate and correct you in my follow-up comment.  I also have many years of interactions like this, where people turn it off once and leave it off and wonder why their future NIFs don't work, so why wouldn't I elaborate when you gave no reason not to?

So, I guess I'm sorry that my need to correct your misquote informed by years of user interaction experiences is somehow combative to you.
