### ISSUE TITLE
NifScope freeze when pressing "Show Collision" button for certain nif

### ISSUE THREAD

**Issue by isshininu** [niftools/nifskope#146]
Certain NIF = NIF with bhkrigidbody data for world models for armors in Skyrim.

How to reproduce:
Press "show collision"

3ds max 2015 64-bit
Niftools plugin 4.0.0.beta3

Create bhkCollisionObject and add armor object, then clone mesh to make bhkConvexShape001 (simple shape type = Convex Shape, Export source mesh checked).

[nif.zip](https://github.com/niftools/nifskope/files/2263771/nif.zip)
[3dsmaxprojectfilesource.zip](https://github.com/niftools/nifskope/files/2263745/3dsmaxprojectfilesource.zip)

**Comment by hexabits** [comment]
It's not freezing.  It's taking a really really really really long time to generate the convex hull for display because **you somehow created a bhkCVS with 9202 vertices**.  AFAIK ***anything over 256 will crash the game.*** 

bhkCVS should generally be under 128 vertices to be considered for use.  Anything more is generally computationally more complex than a mesh shape. 

I have a less naive way of generating the convex hull for display that doesn't take as long to generate,  but it's not ready for release.  Anything over 256 vertices you will start notice increasing the time to display exponentially, and there is nothing that can be done about it.. it's how the algorithm works and it's not a bug.

**Comment by isshininu** [comment]
Ah, I see.
Will try to reduce number of vertices on export and try again.
I am novice at modeling
