### ISSUE TITLE
Req: NIF patcher

### ISSUE THREAD

**Issue by Darklocq** [niftools/nifskope#173]
It just occurred to me that we badly need a fire-and-forget NIF patcher.  That is, take NIF 1, change it and save as NIF 2, run patcher to extract a patch; then anyone else with NIF1 and the patch file can run the patcher to create NIF2.

So many mods are released with conditions against re-releasing files from them (or in the mod in its entirety) even for bug fixes, and this would be a way around that problem. E.g., NIOverride High Heels is superior to the old HDT High Heel system, but innumerable mods are not presently patchable except by experts who know how to do it with manual NIFskope edits.

**Comment by neomonkeus** [comment]
You might want to check out pyffi which has this functionality available already.

**Comment by Darklocq** [comment]
I figured that pyffi was the backend that could make this idea feasible, but it _is_ a backend.  You need to be a supergenius Unix/Linux and Python geek to even figure out what any of that stuff means. (What little documentation it has is in a format most people have never heard of, and it's mostly about theory and about dependencies and compilation.)

I'm talking about putting a GUI front-end on it for Windows people that does just what I described above. Or at least a simple DOS/Powershell command-line wrapper.  A Windows install that has pyffi and dependencies packaged up already, so it just runs out of the box like NifSkope does.  Something the average mod user can handle, about on par with NIFSkope, xEdit, GenerateFNISforUsers, and other utilities that don't expect you to have a CS degree.  :-)  I do have a CS degree, and I think it would take me all week to figure out pyffi.  It won't help with things like what I'm talking about. I can't put up, say, an HDT-SMP patch for an old mod and tell NexusMods users "Install the original mod, then this patch, and just run the patch through pyffi and you're good to go".  Only about 1/10 of 1% would ever figure out how to install the software properly and then use it properly.  And picture Steam Workshop people who don't even use NexusMods.  LOL

PS: I'm too old and broken to attempt something like this.  Python to me is like dubstep - that weird stuff the kids are into. Just figuring out NIFs and ESPs has been like pulling teeth.  "Why couldn't they have done this in Pascal and C?  Where's my cane?  I've fallen, and I can't get up!"  I'm bummed they didn't make the Greybeards a playable race/class.  Ha ha.

**Comment by neomonkeus** [comment]
Seems more like apprehension about learning/documentation issue. Having looked through the docs - https://pyffi.readthedocs.io/en/latest/index.html, I can see why, they is room for improvement to say the least. I understand your apprehension about learning a new tools and I can't say what state that part of the tool is in, but at least it is there, rather than implementing from scratch both backend diff tool and front-end UI through NifSkope.

Pyffi is now distributed on pypi, so from a user perspective they just need to have python installed, then just run `python -m pip install Pyffi`
Pyffi contains some helper scripts called `patch_recusive_make.py` - https://github.com/niftools/pyffi/blob/develop/scripts/patch_recursive_make.py . 
This is just a wrapper for the shel/bat script. 
If you look at the python file. you'll see it takes 3 options `input nif 1 path`, `input nif 2 path`, `output path` so should be a case of calling python ./Scripts/patch_recursive_make.py f1 f2 out

**Comment by Darklocq** [comment]
Right. I'll repeat that I already understand that pyffi is a capable backend to do the patch generation and application.  But the average game player (not software developer) on Windows, especially if mostly a console-game player, isn't going to have python installed and would find it daunting.  So, a simple GUI wrapper is needed.  Imagine if TES5Edit, NIFSkope, FNIS, BSAOpt, and all the other tools mod-users employ were all just barely-documented command-line Python scripts.  Most mods of any complexity would simply not exist, and there would be no community around them to speak of, just a few dozen super-geeks doing stuff with each other.  (Sorry, that sounds kinda like a hairy sex party, ha ha.)

**Comment by Darklocq** [comment]
PS: The introduction at this page gets right to the matter I'm apparently having difficulty conveying: https://opensource.com/article/18/8/pysimplegui
When I get some coffee in me, I may give the rest of that page a try.  I came here because someone trying to set up their own GUI for code administered by this GitHub project seemed counterproductive when it could be centralized. (However, that GUI system doesn't seem to support drag-and-drop, just elements similar to old-school web forms, like text-entry fields and checkboxes, so it may not be good enough for the task at hand).

**Comment by hexabits** [comment]
> this would be a way around that problem

This isn't some bulletproof way of dodging copyright issues as you would seem to think.  Patching is not some impregnable legal bastion.  Here are just two very different ways of looking at patching:

For example, you might enable a person to apply your work to another's.  _**The patch contains your work**_, and that seems fine.  Now, you create a patch that enables a person to apply another person's work to your work or a third party's work.  _**The patch contains the other person's work**_, not yours or the third party's.  In most cases this would mean you're essentially isolating everything that the other person did, and discarding any common data.  This is very clearly not OK as you're still distributing their work.  In the case of NIFs, this could include geometry and animations that they made themselves.  With the block-based layout of NIF files, just because the patch is "binary" doesn't mean their complete work is not wholly, contiguously present in the patch. 

Whether or not your example case is the latter doesn't really matter either, as a patching system would not discern between the two and I'm not particularly interested in a system that makes people think they could include other people's work in their mods **simply because they're not including the entire file**. 

Furthermore, you would appear to be describing simple binary patching, so why not use one of the dozens of binary patchers in existence?  You've written hundreds of words over several comments, much of it detailing the extent of your computer science knowledge and disdain for languages written after 1972, yet you are unable to identify binary patching when you see it?

Your only example details the manual creation of a single `NIF 2` from a single `NIF 1` and distributing a patch for that.  It works only for an exact NIF, and produces the same NIF every time.  This is binary patching, completely file agnostic, and certainly not specific to NifSkope.  There are hundreds of tools that already do this for any binary filetype.

If your example had described the non-manual, automated creation of a `NIF M` from any `NIF N` and distributing a patch _script_, this would have been a very different discussion.  The work you put into developing a script that can convert any `NIF N` to a `NIF M` is your own.  Such a patch script could also take any `NIF P` and any `NIF Q` and describe how to merge them into a `NIF R`.  It would require the person to have both input NIFs and so there should be no issues there either.

Unless you have some use cases for a generic N->M or a generic  P+Q->R,  this should probably be closed as opening NifSkope just to do binary patching doesn't seem very useful compared to a dedicated program.

**Comment by SMB92** [comment]
I have been watching this thread since its inception (subscribed), with what I can only describe as contempt, however that reply Jon was just bloody beautiful.

**Comment by neomonkeus** [comment]
@jonwd7 Good to close this off then?
