### ISSUE TITLE
Non-header nif.

### ISSUE THREAD

**Issue by magickid1234** [niftools/nifskope#187]
Hey there! Nif skope is a great tool and I've been using it for awhile for Aura Kingdom MMD. Lately, the Taiwanese version of the game drops a whole new nif type without a header, so I was wondering if there is anyway to open it. I use nifskope as a convert tool so I need to be able to convert them back into 20.3.1.2.  I have attached examples below where M936 is nif that Nifskope supported, and M956 is the new nif. Thank you very much!

[NIF.zip](https://github.com/niftools/nifskope/files/4976955/NIF.zip)

**Comment by hexabits** [comment]
It does have a header, it just leaves the version number out of the header string.  I thought NifSkope already supported this type of header, but apparently not.  My other tools used for decoding do support that type of header, and the new file is still 20.3.1.2.

Since it's still 20.3.1.2, the format didn't actually change any but it does make use of a weird low number of textures in some of the NiTexturingProperty, which nif.xml didn't anticipate so the included file won't open in NifSkope without two fixes, one to nif.xml and one to NifSkope.

And the official and my own releases don't actually have support for 20.3.1.2 in nif.xml at all, so I assume you're using an XML that was edited to open 20.3.1.2, either from another ticket here or from the old forums.   So since 20.3.1.2 isn't actually officially supported at all, for the XML edits, I would just have to post the edits here. 

![image](https://user-images.githubusercontent.com/170077/88472535-ebf6b980-cee1-11ea-96b6-9efa79997e7b.png)

Just to show that I have it loading after a few XML fixes to NiTexturingProperty (and merging in the 20.3.1.1/20.3.1.2 changes that aren't in nif.xml officially)

**Comment by magickid1234** [comment]
Oh hey! Thanks for the head up! I’m actually using the official build which is v7.0 which supports 20.3.1.2(Maybe that was the old forum idk.) So is there a way to put the header back in hex? Because I’m using like a conversion tool which need the actual header back to normal for conversion! Also, I was wondering since they use a smaller amount of NiTexturingProperty, is there anyway to convert them to 20.3.0.9?

**Comment by hexabits** [comment]
You're right, I apparently did include the experimental changes for 20.3.1.1 & 20.3.1.2 in the 2.0 Dev 7 release.  But these changes never got committed to nifxml, and my own working directory for nifxml no longer includes these changes, and so my Dev 8 release doesn't include these changes either.  While the 20.3.1.1 & 20.3.1.2 changes in nifxml worked fine with NifSkope, they were rather intrusive changes and other projects couldn't support the changes as easily, so the changes for those versions will not officially make it into nifxml, and I tend to make builds using the official version of the XML. 

Hex edits or not, there is still at least one nif.xml edit necessary, so here is the Dev 7 XML modified: 

[nif.zip](https://github.com/niftools/nifskope/files/4977418/nif.zip)

As far as hex editing goes, you just need to add back the version to the header string:

Before
 `47 61 6D 65 62 72 79 6F 20 46 69 6C 65 20 46 6F 72 6D 61 74 0A`
After (add the bold bytes)
 `47 61 6D 65 62 72 79 6F 20 46 69 6C 65 20 46 6F 72 6D 61 74` **`2C 20 56 65 72 73 69 6F 6E 20 32 30 2E 33 2E 31 2E 32`** `0A`

So in text that's

`Gamebryo File Format` `0A`  changed to  `Gamebryo File Format`**`, Version 20.3.1.2`** `0A`

**Comment by magickid1234** [comment]
Thank you so much! problem solved!
