### ISSUE TITLE
Failed to load block number

### ISSUE THREAD

**Issue by magickid1234** [niftools/nifskope#188]
Hello! It's me again, I'm sorry for the trouble. The new NIF.xml works really well to open 20.3.1.2. But when I tried to convert it into 20.3.0.9 using a debug version of Nifskope, although there was no error shown, but when I tried to open the converted file, it shows this error:
"failed to load block number 205 (NiTriShapeData) previous block was NiMaterialProperty
Failed to load Desktop/#b20371.nif"

I have attached the converted gif. Again, I'm sorry for asking too much but I can compensate for your time if you prefer! Thank you!

[converted nif.zip](https://github.com/niftools/nifskope/files/4978572/converted.nif.zip)

**Comment by hexabits** [comment]
Because there are structural differences between 20.3.0.9 and 20.3.1.2, just changing the version number in the header is not going to always do what you want it to.  There is no actual conversion of structure i.e. there is no logic that dictates the process.

Even if you were using a modified NifSkope to change the version string and version number with the NIF file open, and then re-save, it's not necessarily going to work.  

I would like the original #b20371.nif before you edited it though, just because I'd like to compare them.

**Comment by magickid1234** [comment]
Thank you for your reply! I didn't just change the number of the header, there were actually changes made in structure. I've attached the #b2037 which was original, and #b20372 which was the first conversion file (20.3.1.1). So in order to use the files, I usually have to convert 20.3.1.2 to 20.3.1.1 using hex and then convert to 20.3.0.9 using the debug version of Nifskope.
[Original.zip](https://github.com/niftools/nifskope/files/4978749/Original.zip)

**Comment by magickid1234** [comment]
Hello, do you have discord or anything where I can contact you directly? Thanks

**Comment by magickid1234** [comment]
[nif.zip](https://github.com/niftools/nifskope/files/5008656/nif.zip)
Here's the Nif.xml that I used to convert 20.3.1.1 to 20.3.0.9
