### ISSUE TITLE
Browse Archive not opening any archive at all.

### ISSUE THREAD

**Issue by Marcurios** [niftools/nifskope#194]
Like the title says, if i want to open a ba2 file, not a single thing happens, except for the ba2 files that belong to the CC mods, they state that there are no meshes in that ba2 file, all other ba2 files just don't open, not a single one.

have the latest version here.

**Comment by hexabits** [comment]
The BA2 in question needs to have a `meshes` folder or it's not going to show anything at all.  The Browser is for browsing NIFs. 
 Based on what you said about the CC archives, it sounds like you're trying to open up non-mesh BA2s, which won't show anything naturally since they have no NIFs. 

If the BA2 fails to open or doesn't exist (if selecting from Recent Archives dropdown for example), you will see an error message.  So your BA2s are in fact opening just fine, since you haven't mentioned such an error message. 

There's really not any info I can go off of otherwise. 

I'll throw out a wild guess and suggest you might only be trying to open your own BA2 files, and you're not using any kind of organization (all your files in the `meshes` root folder).  The browser doesn't show NIF files in the root folder, only subfolders.

**Comment by Marcurios** [comment]
I know that, like i said, it's not opening any mesh from any mesh folder.
I always do research before i post bug reports.

I said this about the cc files cause it shows that i can slelect a ba2 file to open, cause i tried to open them all one by one, and all the game's regular (main - with meshes) bsa's just don't open at all.

so when i said not a single one, it should have told you that i tried all the "file -main.ba2" files which hold the mesh folders.
i tried every single one, not 1 opens. and plenty of them had a mesh folder.

I have been modding FO3, FNV, FO4 and Skyrim and SSE since they came out, i know what i'm doing.
Not to brag, but to make you realize that i know how to work with nifskope.

**Comment by hexabits** [comment]
I can only manage to throw out guesses, because as described (and making some general assumptions about info you haven't provided) what you detailed simply isn't possible.  If they don't open, you will get a `nifskope.io` error message.  If they don't tell you there are no meshes, and there is no other error message, then it opened. 

My random guess is now: 

You've somehow got corrupted UI settings stored by the program and it's merely a display issue.


Find and delete this key in your registry: 

`HKEY_CURRENT_USER\SOFTWARE\NifTools\NifSkope 2.0\UI`

**Comment by Marcurios** [comment]
Yep, that did the trick, i can now see the contents of the ba2 file in the left pane.
Thanks !
