### ISSUE TITLE
Feature Request: Ability to copy and paste Starfield mesh sub-record / tree

### ISSUE THREAD

**Issue by JMPZ11** [niftools/nifskope#244]
Presently, the Starfield blender plugin exports each LOD as a separate BSGeometry record with only LOD0 populated.

When I right click on the mesh item(s) the only option available is block -> convert. No copy or paste branch. Ideally I would like to be able to copy from and to any LOD# - but mainly 0 -> 0,1,2,3. The bounding sphere, bounding box, vertex stats and such.

Recombining the meshes is virtually impossible (because I suck and copying and pasting numbers over and over lol)

If there was a way to provide an export / import to json / yaml, it would greatly simplify some of these things that would be best handled with scripting. Also open to other ideas - the blender plugin uses a dll that can convert between nif and JSON - so maybe there is a tool / library?
Thanks as always!

**Comment by fo76utils** [comment]
Unfortunately, copying and pasting branches is a block level operation, and it does not seem to be implemented for sub-records of a block, like mesh data in the case of BSGeometry. At the least I fixed the Update Bounds spell on my fork so that it works on Starfield and Fallout 76 meshes now, it recalculates the bounding sphere, bounding box, and vertex and triangle counts so only the paths and flags need to be set manually.

There is a Python library for manipulating .nif and other related formats, in theory, that could be used for automated processing, although as far as I know, it has not been updated for games newer than Fallout 4. But other people like @Candoran2 are more familiar with this topic.

Ideally, the issues would need to be fixed in the Blender plugin so that it exports the models correctly in the first place.

**Comment by JMPZ11** [comment]
It's fine, I fixed the plugin - mostly. Fixed the material truncation and got it to put the lods in the right place... but it still leaves all the extras. I've never been a fan of position-based indexes... But I'll have it pretty well cleaned up here shortly. I'll go ahead and close it - thanks so much for your help - I'm sure I'll be pestering you again :)
