### ISSUE TITLE
Batch normals update

### ISSUE THREAD

**Issue by ghost** [niftools/nifskope#253]
Need option for batch normals update. For all blocks in nif file. Like tangents update.

**Comment by fo76utils** [comment]
I added batch versions of Face Normals and Smooth Normals in my fork of NifSkope in [this build](https://github.com/fo76utils/nifskope/actions/runs/10432892078).

**Comment by Mitradis** [comment]
Amazing!

**Comment by Mitradis** [comment]
@fo76utils crashing on meshes\dlc01\architecture\dawnguard\dinttowerstairs02.nif

**Comment by fo76utils** [comment]
It does not crash for me with either version of Skyrim, can you provide more details about how the issue can be reproduced?

If you have an older CPU, note that the Actions builds use AVX and F16C instructions by default, but the release packages include a separate NifSkope\_noavx.exe for compatibility.

**Comment by Mitradis** [comment]
Sorry. My mistake! I experimented with the BSA archives and forgot to remove.

**Comment by ghost** [comment]
@fo76utils possible increase zoom scroll speed, like in Dev7?

and possible remove this? 
![image](https://github.com/user-attachments/assets/76e8b457-d343-43f7-924d-56b8cf81e0f4)
like in Dev7. because it creates a useless empty area. does not give full width.


Block Details Height not saving.
![image](https://github.com/user-attachments/assets/0bdf1a0e-e6da-49a6-867d-ffee6eed5f89)

**Comment by fo76utils** [comment]
> @fo76utils possible increase zoom scroll speed, like in Dev7?

This can be done easily, although it may be better to make it configurable.

> and possible remove this?

I moved the shader property data in BSLightingShaderProperty and BSEffectShaderProperty to a separate structure because of how newer games (Fallout 76 and Starfield) handle materials. In those, everything after Controller is cut off if the name of the block (used as a material file path) is not empty. So, moving the data to a sub-structure allowed for easily making all the remaining fields conditional and also for defining separate structures for each game. I could try implementing this in a way that does not involve using a sub-structure for older games, probably by adding back all the data fields with version <= Fallout 4 conditions added.

> Block Details Height not saving.

Is there a version of NifSkope where this is working, so I can use it as a reference?

**Comment by ghost** [comment]
@fo76utils in Dev7 Block Details Height is saving.

**Comment by fo76utils** [comment]
[This update](https://github.com/fo76utils/nifskope/actions/runs/10475346960) includes fixes to the above issues:

* Zoom speed is now configurable in the render settings. This affects the mouse wheel in both the main window and UV editor, as well as Page Up/Page Down in the main window, and right click dragging in the UV editor. The default (8) is similar to the previous release, increasing the number by 2 doubles the speed.
* Shader property data is no longer in a sub-structure for Skyrim and Fallout 4.
* The geometry of docked widgets not being restored is apparently a Qt bug (when recompiled with the current Qt 5.15 version, dev7 also has the same problem), but it could be worked around.
