### ISSUE TITLE
Untickable item in bitflags

### ISSUE THREAD

**Issue by ttl269** [niftools/nifskope#51]
In case that in nif.xml there is `bitflags` component containing only one `option`, its item in NifSkope is untickable.

Example: meshes\terrain\blackreach\blackreach.4.-3.-1.btr
1. Edit any value located in `BSSegmentedTriShape > Segment > Flags`.
2. Select `BSSEG_WATER` and complete edit.
3. Edit value again and attempt to untick the value.

---

It actually goes beyond just `bitflags` with one `option`.

Example: BSLightingShaderProperty.  
1. Untick all options in SLSF1. Complete the edit.
2. Edit again, select only ~~one~~ the first option e.g. SLSF1_Specular.  Complete the edit.
3. Edit again, try to untick the ~~one~~ first option. 

To untick them all again you must ~~tick~~ hover over a second option's checkbox and then the first checkbox works.  This is why `bitflags` with one `option` can never work.

This means that it's not a data issue but a UI issue.  Basically the UI logic for the checkbox is not getting initialized until you mess with other checkboxes.

---

Edit:  Seems to only happen when leaving only the first option in the list checked.  Checking/unchecking the second option only works fine, e.g. SLSF1_Skinned.
Edit2:  Actually you only need to **hover** on another checkbox, not tick it, and then you can untick the first option.
Edit3:  Actually, if you carefully attempt to hover on **any singularly checked checkbox** no matter the index in the list, it is seen as inactive until you hover over any of the other checkboxes.  So if you have only one checked option, it can be anywhere in the list.  When you expand the dropdown, be careful not to hover on any item other than the checked one.  You cannot interact with this item until you hover on another item in the list.

**Comment by hexabits** [comment]
@ttl269 Can you provide more context?

~~I assume this is happening with 1.1.3 and "old" nifxml (0.7.0.0)?  The new nifxml introduces a couple incompatibilities with the NifSkope codebase e.g. collision layer wire colors.~~

~~It sounds though that this is a longstanding issue so in that case can you provide example NIFs or point out, or NIF filenames?  (I only have Skyrim installed at the moment, though I will get around to reinstalling the earlier games soon now that I have more space.)~~

~~It seems currently only `BSSegmentFlags` applies, and if I were to guess that might be in the BTR/BTO files.  I will look there, but otherwise can you provide examples?~~

---

I did an ASCII search in my Skryim assets for `BSSegment` and found some results.

If I double click on the edit area (it is '0' by default) and select the option,  I indeed cannot untick it afterwards.

---

Updated main issue description.
