### ISSUE TITLE
OBJ Import Error

### ISSUE THREAD

**Issue by neomonkeus** [niftools/nifskope#74]
Reported by Tamira

Unable to import .obj correctly.
UV data is not maintained.

The newer Nifskope versions from Version 1.1.0-rc7 on do not longer support the import of obj files as the UV is messed up.
The last Nifskope version that could handle obj import properly was Version 1.1.0-rc6 (from 02/2012 !)"

Link to file used : https://www.dropbox.com/s/e5txp7b5053o4n1/poorfolks_cottage.obj?dl=0

![02](https://cloud.githubusercontent.com/assets/525919/4975772/ba8c56ee-68d4-11e4-9b40-b1c38aed0b2a.jpg)

**Comment by hexabits** [comment]
Did we not fix UV imports in niftools/nifskope@f6fc4e5172cfc8597c8cea45f77a7d634790be7d ?

I didn't have any issues with UV imports after that.  I would suggest using a more reliable OBJ for testing.

**Comment by neomonkeus** [comment]
Tamira seem to think this is not working, even with the latest version that you have provided.

**Comment by hexabits** [comment]
I believe something is wrong with that OBJ in particular, in addition to any UV issues.  I just attempted a few OBJ imports of my own and UVs imported just fine. 

The errors listed, "Invalid indices" means something is wrong with the vertex and triangle data.  Not the UVs.

This is because the OBJ importer is a wreck and honestly I wonder sometimes if it should be kept.  The proper, reliable way to import data into NifSkope is to use Max/Blender plugins to create a NIF.

**Comment by ttl269** [comment]
@jonwd7 I just reviewed source codes of obj.cpp from older versions of Nifskope and found weird change in it between version 1.1.0-RC6 (I can confirm that OBJ import works ok includind UVs) and version 1.1.0-RC7 (I can confirm that OBJ import is broken).
**Code from RC6 - working version:**

```
if ( ix == points.count() )
{
    points.append( p );
    verts.append( overts.value( p.v ) );
    norms.append( onorms.value( p.n ) );
    texco.append( otexco.value( p.t ) );
}
tri[t] = ix;
```

**Code from RC7 and later versions - broken:**

```
if ( ix == points.count() )
{
    points.append( p );
    verts.append( overts.value( ix ) );
    norms.append( onorms.value( ix ) );
    texco.append( otexco.value( ix ) );
}
tri[t] = p.v;
```

Can you take a look at it? Couldn't it be the source of OBJ import problems? Can you try to compile Nifskope with that older code? In your present code it is at [line 798](https://github.com/jonwd7/nifskope/blob/dev/2.0/src/importex/obj.cpp#L798) of obj.cpp file.

**Comment by SACarrow** [comment]
I made the mods that @ttl269 noted above in my cloned repo and indeed they seemed to fix the issue of UV map distortion. Since I have very little git experience and I cloned from the main dev branch and not the branch of @jonwd7 I won't try to submit anything.

BTW shouldn't NifSkope 1.2.0 just be released? What functionality is missing?

**Comment by neomonkeus** [comment]
@SACarrow - 1.2.0 was to be used as a stable feature branch, where features from the experimental 2.0 branch which didn't break compatibility could be backported.

I would branch off and create a fix, then you can create a pull request against whatever branch is most appropriate. Good git practice ;)
