### ISSUE TITLE
Fix .obj import uv data support

### ISSUE THREAD

**Issue by neomonkeus** [niftools/nifskope#8]
The uv data gets corrupted on load. 

This is possibly due to the convention issues with .obj but also results in 
"Could not load texture data for UV editor." 

More information available here - http://niftools.sourceforge.net/forum/viewtopic.php?f=38&t=3210

**Comment by neomonkeus** [comment]
Closed by #9

**Comment by hexabits** [comment]
It was not in that pull request.  That's why I still have it as a feature branch.  Probably saw the "Edit UV" stuff instead.

There's nothing keeping me from opening a pull request if you want me to.  I just figured I would end up fixing more stuff while I was in there, but I will probably not be touching the import/export stuff for a while.

**Comment by neomonkeus** [comment]
Yeah I was just browsing old issues to see if they were closable. I actually will be opening an issue on "Edit UV" once I get the chance. I think it would be good to merge anyway as this is a priority issue for people who use .obj.
