### ISSUE TITLE
Translation discrepancy (possibly w/ skinned meshes)

### ISSUE THREAD

**Issue by hexabits** [niftools/nifskope#80]
I noticed a while back a discrepancy in the X/Y positioning of a certain mesh.  In the CK Preview it appears correct and in NifSkope it does not appear to be centered.  ~~However, I am not sure which is correct.  I would need to put the mesh I am testing with in game, or at least in the CK proper.~~ _See bottom._

[Test mesh](https://drive.google.com/file/d/0B9F4jSOO-JcpOWZSdHdiMnRoM1E/view?usp=sharing)

CK Preview:
![atronachflame_ck](https://cloud.githubusercontent.com/assets/170077/5715268/4a3bcdbe-9aa4-11e4-92c8-aa87b767203c.png)

NifSkope:
![52ffc84c-9aa4-11e4-9089-cde00ec0d71a](https://cloud.githubusercontent.com/assets/170077/5745586/f59bd6aa-9bf7-11e4-90d7-7f3d83480ba8.png)

Now it appears to get it looking "correct", I must zero out the X and Y translation on the meshes.  Why this is I am unsure.  It could do with ignoring such values when using an `NiSkinInstance` or it could be more subtle.

NifSkope (w/ X and Y values zeroed):
![bdaf4136-9aa4-11e4-9d5c-e331d79de28c](https://cloud.githubusercontent.com/assets/170077/5745589/f8f7b0ee-9bf7-11e4-8058-5274d0f96a64.png)

**_There is no visual difference in CK Preview when zeroing the values**_

~~To confirm this is even a bug on NifSkope's part, it must be confirmed there is no neck gap on the test mesh in game or in the CK proper.  If there is a gap, then the bug actually likes with the CK Preview.~~  **_There is no gap and no visual difference in CK proper when zeroing the values**_

**Comment by hexabits** [comment]
Oh, calling on @ttl269 for input.  You may be able to figure out if it's an issue and why before I can. :)

**Comment by hexabits** [comment]
OK, zeroing the Z value of the `NiTriShape` also has no bearing in the CK.  It does however have a dramatic bearing on the display in NifSkope.

So where is the CK getting the Z height from?

---

OK, it seems that changing the **Translation** in `NiSkinData` > **Skin Transform** does nothing for the positioning in the CK either.  I changed the -60 Z to +60 Z and there was no change in the CK.

But changing the **Skin Transform** values _does_ have an effect in NifSkope.

**Comment by hexabits** [comment]
I have tested with other meshes that have many skinned parts, and changing any of the Translation (on `NiTriShape` or in `NiSkinData`) values does not affect the appearance of the skinned mesh in the CK or in game.

So, is this because it is a skinned mesh?  I would assume yes.   But looking through the code, NifSkope goes to great lengths to include such translations for skinned meshes.

**Comment by ttl269** [comment]
@jonwd7 Translation on `NiTriShape` and `NiSkinData` don't affect the position where the skinned mesh is rendered. I think that it is determined by bone positions and their influence on vertices.
But from yesterday's testing it seems that these transformations has influence on rendering engine when deciding what render and what not (what is in view area and what not). If the mesh - after all transformations as they are taken int account by Nifskope - would get out of engine's view area, the mesh is not rendered even if it's render position (determined by bones and their influence) is actually in viewable area.
Try [this testing mesh](https://drive.google.com/file/d/0B74aIy1KTJ-9RExnX280WS1lekk/view?usp=sharing).
After opening it in CK preview and disabling ground, you get:
![testatronach1](https://cloud.githubusercontent.com/assets/2514993/5743874/5fad8240-9c1c-11e4-94d5-a60235d80d54.png)
Vanilla _skinned_ atronach armor and head mesh have modified Translation of `NiTriShape` and `NiSkinData`, so they are rendered out of right position in Nifskope, but they are rendered ok in CK. I have added two green meshes for visual help - armor and head. They are _not skinned_ (just usual meshes) and shifted to same position as _skinned_ atronach armor and head are rendered in Nifskope, so you can see also in CK preview actual (=after all transformations in `NiTriShape` and `NiSkinData`) position of _skinned_ armor and head.
And now start moving atronach to right until green armor is out of view area:
![testatronach2](https://cloud.githubusercontent.com/assets/2514993/5743983/3a96bb2e-9c1d-11e4-86ba-e5334fe66bb8.png)
After a while also _skinned_ atronach armor disappear even if it should still be visible. That is because its actual (=after all transformations) position is out of visible area.
Same "disable" effect you can get with head when moving its green mesh out of view area.
This behavior is same also in real game.

So, I think that it is good that Nifskope take into account all transformations on `NiTriShape` and `NiSkinData` when computing its position. User can visually verify skinned mesh actual position.

**Comment by hexabits** [comment]
@ttl269 

> So, I think that it is good that Nifskope take into account all transformations on NiTriShape and NiSkinData when computing its position. User can visually verify skinned mesh actual position.

But the "actual" position is a bit meaningless when changing either the `NiTriShape` translation or the `NiSkinData` translation has no effect on the position in the CK or in-game.  When there are slight differences in the `NiTriShape` / `NiSkinData` (it is usually just a negation of the `NiTriShape` values because it is rotated -180 degrees) you end up with incorrect gaps like the atronach head, whereas in game it is fine.

Here is a test case: [steamcenturion.nif](https://drive.google.com/file/d/0B9F4jSOO-JcpQlJ3Zy11R0FBT0E/view?usp=sharing)

NifSkope:
![steamcenturion broken_20150114_14-09-35](https://cloud.githubusercontent.com/assets/170077/5745536/8f5d4bb2-9bf7-11e4-8550-5e7223ec58e1.png)

CK:
![steamcenturion broken_20150114_14-09-35_2](https://cloud.githubusercontent.com/assets/170077/5745543/944c5d3e-9bf7-11e4-978f-0e097b945b9a.png)

The difference is that I arbitrarily negated the **Skin Transform** values.  You can see it's now completely broken in NifSkope, and not representative of in-game.

I can try to mimic the visibility culling behavior though, by transforming the bounds of the meshes by these values.  Or having some kind of "ghost shape" mode which shows the real positions.  Or just toggling between applying and not applying the skin transform to the visible mesh.

**Comment by ttl269** [comment]
@jonwd7 

> The difference is that I arbitrarily negated the Skin Transform values. You can see it's now completely broken in NifSkope, and not representative of in-game.

I think that it is good that it is broken in Nifskope - it is evident, that something is not ok. Because it is no ok. It will be rendered ok in game but under specific angles/distances the head will not be rendered as I described above. Try to move that centurion a little up, you get:
![centuriontest](https://cloud.githubusercontent.com/assets/2514993/5747232/d938d7b2-9c36-11e4-9a36-74c193905289.png)

> But the "actual" position is a bit meaningless when changing either the NiTriShape translation or the NiSkinData translation has no effect on the position in the CK or in-game.

But it has effect on whether game engine render that part or not. Maybe I used wrong word "actual" - it should be "position not affected by bones" instead. Because it seems that right that position game uses for decision if render or not render that mesh.

> Or just toggling between applying and not applying the skin transform to the visible mesh.

Good idea.

**Comment by hexabits** [comment]
This was actually addressed in 3abb396749579f7884413d68cf9a828a7e64c171 and ef1a9bceac4a6fb614a8583c3bc954e43f74608a , which allow you to see the skinned and unskinned view of the vertices. 

Further visualization options to match the BSShape class for FO4's skin data are planned but will be a separate ticket.
