### ISSUE TITLE
Fallout 4 - Header Error

### ISSUE THREAD

**Issue by Cynosphere** [niftools/nifskope#89]
Gives ""failed to load file header (version 14020007, 20.2.0.7)""  when trying to open a Fallout 4 model.

**Comment by hexabits** [comment]
We're aware, obviously.

**Comment by neomonkeus** [comment]
@LUModder F04 has only been out for a few days, support will take time. The whole tool chain needs to be updated to add support. The first step is decoding the format and updating our format description (nif.xml). There has been a lot of changes to fundamental components of the structure. That said, there is a hive of activity at the moment with several people working collaborative across several nif communities making lots of progress,

@jonwd7 I put this on hold so that people can see it rather than closing outright.

**Comment by hexabits** [comment]
Progress

![untitled-1](https://cloud.githubusercontent.com/assets/170077/11218585/cd6be33c-8d23-11e5-866a-3ce9cb1eed16.png)

**Comment by anotio** [comment]
Cool ! Could the Team just post a beta version ? Some (like me) just need to open Fallout 4 .nif and export meshe as obj (for paint support in 3d application)

**Comment by hexabits** [comment]
@anotio  Yeah, well, the OBJ exporter doesn't "just work" like you might think.  In fact I've disabled the import/export because people will assume they can use it on FO4 meshes.  The vertex format is completely different and would require a lot of work updating the import/export functions.   However they are currently in such a state of disarray that I'm just looking at using an import library that can handle a lot of different formats so that I don't have to deal with writing directly from NIF to OBJ for example.

**Comment by anotio** [comment]
Yeah, I understand. Hope you'll work well and post a new beta version as soon as possible. I'm 3D artist so i can't help you, but i support you ;)

**Comment by daforce1984** [comment]
Awesome!

I hope you guys could provide a tool  to convert nif to obj for batch conversion.

**Comment by daforce1984** [comment]
Or a command line converter would be much appreciated. Keep up the good work!

**Comment by PillowyGiant** [comment]
Do we have any idea on when this bad-boy will be out?

**Comment by neomonkeus** [comment]
I don't want this issue to turn into a dumping group for overall F04 support. We will make available a version with header support, but we can't be reasonably expected to have full support within 2 weeks of launch? I have narrowed the scope of the issue request.

Edit : Closed issue by accident. Will be closed properly only when code merged to develop branch or build available at @jonwd7's discretion

**Comment by Lord-Sigrah** [comment]
was there ever any resolution to this?  I have had the same issue and cannot open .nif files for Fo4.

**Comment by Cynosphere** [comment]
There's a build that someone put out that opens it, iirc it's linked in
this issue somewhere.

EDIT: https://github.com/jonwd7/nifskope/releases/tag/v2.0.dev4#downloads_2_0_dev4

**Comment by neomonkeus** [comment]
@jonwd7 Can we close this?
