### ISSUE TITLE
[dev5] Refactor regressions

### ISSUE THREAD

**Issue by Ethreon** [niftools/nifskope#92]
[_edited by jonwd7_]
1. Crash when updating array that previously had 0 children.
2. Grayed out array children when increasing the array size.
3. Ctrl-Up/Down no longer works correctly

[_original message:_]

Hi

With the new version, adding a BSConnectPoints::Parents block and trying to add new snap points to it results in Nifskope crashing when updating the array. Any ideas why?

**Comment by hexabits** [comment]
I'm not having the crash issue.  I can add connect points just fine.  Though I do know about an issue with rows being greyed out after increasing the array size.   Can you tell me the specific file this happens on for you?

So to be sure you're using dev5?  Did the filename end with a `-1`?  I initially released, took it down for an issue, re-released and then updated the package.

**Comment by Ethreon** [comment]
Downloaded the latest available package last night just to make sure I have the right tools. 
Example of files where nifskope crashes
Meshes\Interiors\Diamond\ShackParts\ - any of them.
I have tried on random other items from various folders - it insists on crashing. I cannot think of what the issue is, as it worked fine until last night. Aside from me downloading the files again. This is the file I downloaded NifSkope_2_0_2016-04-11-1.

I experience the greyed out issue as well, which usually requires reopening the file.
I also (accidentally) found this when working on some items. Basically, I was trying to copy a trishape to a new file so I can then move it around as I needed, so I created a new file and inserted a ninode. When pasting the trishape, this happened
https://gyazo.com/1d8d92d3d90d4357244fcd163c1105f5

**Comment by hexabits** [comment]
> I cannot think of what the issue is, as it worked fine until last night. 

Just to repeat my disclaimer from the release notes:

> Please note that there could be unforeseen issues with my partial refactor of the NIF loading. This is the first update where I've changed the underlying data/model classes.

Basically all the stuff like Insert, Copy, Paste, are implemented rather poorly, using the Spells system.  Even Update Array is a Spell.  I had to get my partial refactor of NifModel out so that I could use the proper XML definitions for the vertex data, and didn't have time to test how every single block manipulation Spell was going to handle it.   Especially considering I also intend to replace them all with better functions anyway.

I misunderstood about the connect point issue.  You're also inserting the block, I didn't do that.  I indeed have a crash with a new block and updating the array, so I will be able to debug and fix it.

The last thing is intended.  Your startup defaults for NifSkope are set to Oblivion's version.  If you want Fallout 4 as the startup default you need to change it to match in Settings > General > NIF.

**Comment by Ethreon** [comment]
I understand the disclaimer, and that this is an alpha, not blaming the software, just trying to find help. You provided. Thank you. Until the fixes are implemented, I can copy the CPA block from another nif, then paste and modify as desired.

**Comment by hexabits** [comment]
> I experience the greyed out issue as well, which usually requires reopening the file.

Also, a workaround for now (when the array length was not 0 previously) ... if you just double click in the Name field on one of the array rows, e.g. "Connect Points" and then click out of it, the array will update and the new array child you added won't be greyed out anymore.

I have found the crash issue and fixed it.

**Comment by Ethreon** [comment]
Great news!

**Comment by hexabits** [comment]
I have updated the release.  Verify the issues we discussed in here are resolved for you and I will close this. :)

**Comment by Ethreon** [comment]
Downloading now.

**Comment by Ethreon** [comment]
Works. You can close it. Thanks for the update!

**Comment by hexabits** [comment]
Fixed by b215b42.  Closing.
