### ISSUE TITLE
Getting constant crashes with (edited) Fallout 4 .nifs.

### ISSUE THREAD

**Issue by InConSciOUS** [niftools/nifskope#96]
(EDIT: Skip further down, unless the windows crash reports are important; this seems to be a very odd issue that is most likely unique to me. Hope you can help; I'd really appreciate it, as none of it makes any sense.)

Hey there, I just updated to Pre Alpha 5, and now when loading Fallout 4 .nifs, I get crashes 9/10 times. Not sure what happened, there, but it seems like something's definitely up.

Here's a (windows) crash report, included, if it matters.

![nifskope crash log](https://cloud.githubusercontent.com/assets/20087824/16265491/ab3078b6-384d-11e6-881f-172368e0dfea.png)

(Is there a NifSkope crash log? Edit: Couldn't find one, so I assume not.)

Thanks for checking this out. :)

---

(Edit No. 1 -- )
Also, here's another photo of me loading a certain .nif from Fallout 4 Meshes archive and crashing. And I also have a copy of it (and a few others that cause crashes) on the recent files list, and edited copies of them in the Fallout 4\Meshes\Data folder.
It actually only seems to be doing this to .nifs that were created -- not even edited -- before Pre Alpha 5, and, for some reason, even if it's the original, non-edited, good old original mesh.

(I'm quite confused as to why this is happening.)

![nifskope crash 2](https://cloud.githubusercontent.com/assets/20087824/16265727/fd68711e-384e-11e6-8582-18ad90dd502f.png)

---

(Edit No. 2  ((Importante, I believe)) --

Okay, I went searching through my AppData folders to see if something was up, and as it turns out, NifSkope is creating empty versions of the loaded .nif, all of a sudden, upon crashing.

Apparently, it's not an issue with NifSkope pre-alpha 5, because the same happens with 4.
So, if it's just a problem on my side, do you have any idea what it would be?

Here is (yet another) screenshot of the empty .nifs in my AppData\Local\Temp\NifSkope folder --
(Two of which were created from opening a .nif from the Fallout 4 mesh archive, oddly enough.)

And, finally, this only happens with IndustrialCart01.nif and FoundryCart01.nif, which I've been trying to edit and open with NifSkope after converting them with Elrich after editing them with 3DS Max.

Do you have _any_ idea why NifSkope is acting this way towards two files specifically?
It actually effects any file that contains similar BSTriShapes or "IndustrialCart" or "FoundryCart" in it.
It's really confusing, and getting on my nerves, since it literally makes no sense (to me).

![nifskope creating empty nifs](https://cloud.githubusercontent.com/assets/20087824/16268692/55655f68-385d-11e6-9f68-a3e1e22d76e8.png)

Thanks for any help you can give. I wouldn't have made this an "issue" if I knew it was something on my side, and I'm still not really sure if it is. But, thank you, regardless, for your work on NifSkope. :)

**Comment by hexabits** [comment]
This isn't the place for bug reports on developmental releases.  Re: your very top Edit, this also isn't the place to help you with resolving the issue either.  That is what the Issues on my own repo and the niftools forums are for. 

The AppData thing is different from your assumptions.  It's not creating a file _upon_ crashing.  I added a file checker which immediately saves a copy of the NIF after loading, and compares its checksum against the checksum of the original file, to look for any data integrity issues.

Given the file is 0KB and your other image shows that the file is already loaded, but is at 0% through saving, it's likely crashing _from_ the file check. 

However, I've had the md5 checksumming in NifSkope since December.  You left out the most important information which was what version were you using before Pre-Alpha 5.  Apparently not dev4 since it still happens to you when downgrading.

So, there is a good chance that it's very platform specific, though I'm on Windows 7 too and have zero issues opening files from archives or otherwise.  This will likely not do anything but you can try running as administrator.  Should not be necessary though since the point of AppData is for apps to write to it.

Anyway.  If it is the file checking causing issues for you,  I have already removed the feature for other reasons and so in the next release it will no longer check against a copy saved to AppData.

You can try this pre-pre-dev build which has the checksumming removed:  
\<removed as the public release has had this for some time\>

Fair warning that this build is not meant to be a public release and so I make no guarantees if you are to use it day-to-day.  It has known issues that I have not yet resolved which are blocking a release.

**Comment by InConSciOUS** [comment]
I appreciate your response, very much, and it wasn't until after posting that I realized this was not a place for bug reports. I apologize for that. I will use the suggested forums from here on. 

I'm new to GitHub, honestly, and I've not become accustomed to the way things work here.
I simply Googled my issue, came up with another post here, and thought that I might seek help here. I apologize if I wasted any of your time; that was most definitely not my intention.

I also neglected to mention (I was very tired) that this only started occurring after creating/editing a mesh in 3DS Max, running it through Elrich, and then opening it in NifSkope, and that I did update from Pre Alpha 4 to Pre Alpha 5, but I updated **after** the crashes started happening, as I assumed that the newer release may have some added 'compatibility' with converted .nifs, but it continued to happen.

I'd just like to say that I appreciate your work on NifSkope, as well as the work of others involved. I've been using it for about 8 months, and this is the first time I've come across such an issue, and I'm fairly certain that I, myself, caused it, possibly due to relocating my AppData\Local folder. 

(NifSkope created a new folder for itself in the previous AppData location, and is using that, rather than the location I redirected the folder to. So NifSkope isn't aware that I relocated the folder, though I'm not quite sure why that would cause this rather odd "issue" to occur.)
Which, thinking about it now, I also neglected to mention.. I had been up for over 24 hours. Sorry.. 

(Even though the crashes did not start occurring until days after I did so, and even then, not until after I tried to open converted/edited meshes.)

By the way, the pre-pre-dev build link you sent me works great. 
At least I can do what I need to do, now. Thank you very much.

(Also, this may not be important at all, but I thought I should let you know (just in case) that I got a "shader compilation error" with the build you linked.)

Again, thank you very, very much, and I apologize if I wasted your time.
Take care, and have a great day/night. :)

**Comment by StormFX** [comment]
I may be wrong here, but could it be because you're attempting to load a file that's in an archive? That would explain the 0 bytes file(s). Try extracting the file first.

**Comment by neomonkeus** [comment]
@StormFX NifSkope supports loading from archives.

**Comment by hexabits** [comment]
The versions which have the md5 checksumming save out the file to the AppData whether or not it's in an archive.  Again, I've since taken it out anyway so it's a moot point.

It was 0KB because it was crashing the moment it created the file to write to.

**Comment by StormFX** [comment]
Ah. My apologies. I've never had any luck opening from an archive, especially large ones. Thanks for the info. :)

**Comment by hexabits** [comment]
Closing as this was resolved long ago by removing the file checking.
